{% set name = "kent-tools" %}
{% set version = "438" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ucscGenomeBrowser/kent/archive/refs/tags/v{{ version }}_base.tar.gz
  sha256: faeaf46551eae87f4be8f6be4d1ddaa93c1ef6d52419f6a44a4759507f0d672b

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - binutils
    - libpng
    - mariadb
    - make
    - rsync
    - zlib
  host:
    - libpng
    - mariadb
    - openssl
    - util-linux #[linux]
    - zlib
  run:
    - libpng
    - mariadb
    - openssl
    - util-linux #[linux]
    - libzlib

test:
  commands:
    - addCols 2>&1 | grep -q "addCols - Sum columns in a text file."
    - ameme 2>&1 | grep -q "ameme - find common patterns in DNA"
    - autoDtd 2>&1 | grep -q "autoDtd - Give this a XML document to look at and it will come up with a DTD"
    - autoSql 2>&1 | grep -q "autoSql - create SQL and C code for permanently storing"
    - autoXml 2>&1 | grep -q "autoXml - Generate structures code and parser for XML file from DTD-like spec"
    - ave 2>&1 | grep -q "ave - Compute average and basic stats"
    - aveCols 2>&1 | grep -q "aveCols - average together columns"
    - axtChain 2>&1 | grep -q "axtChain - Chain together axt alignments."
    - axtSort 2>&1 | grep -q "axtSort - Sort axt files"
    - axtSwap 2>&1 | grep -q "axtSwap - Swap source and query in an axt file"
    - axtToMaf 2>&1 | grep -q "axtToMaf - Convert from axt to maf format"
    - axtToPsl 2>&1 | grep -q "axtToPsl - Convert axt to psl format"

about:
  home: https://genome.ucsc.edu/
  license: MIT
  license_file: LICENSE
  summary: Utilities for the UCSC Genome Browser
  dev_url: https://genome.ucsc.edu/

extra:
  recipe-maintainers:
    - danielnachun
