schema_version: 1

context:
  version: 501

package:
  name: kent-tools
  version: ${{ version }}

source:
  git: https://github.com/ucscGenomeBrowser/kent.git
  tag: v${{ version }}_base

build:
  number: 0

requirements:
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - if: linux
      then:
        - binutils
        - gcc
    - make
    - rsync
    - sed
  host:
    - bzip2
    - htslib
    - libcurl
    - libiconv
    - libpng
    - mariadb >=11
    - openssl
    - if: linux
      then: util-linux
    - zlib
  run:
    - mariadb >=11

tests:
  - script:
      - test -f $PREFIX/bin/bigWigToBedGraph

about:
  license: MIT
  license_file: LICENSE
  summary: Utilities for the UCSC Genome Browser
  homepage: https://genome.ucsc.edu/
  repository: https://genome.ucsc.edu/
