#!/usr/bin/env bash

set -o xtrace -o nounset -o pipefail -o errexit

cmake -S . -B build \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_VERBOSE_MAKEFILE=ON \
    -Wno-dev \
    -DALGEBRA_PLUGINS_USE_SYSTEM_LIBS=ON \
    -DALGEBRA_PLUGINS_INCLUDE_EIGEN=ON \
    -DALGEBRA_PLUGINS_INCLUDE_FASTOR=ON \
    -DALGEBRA_PLUGINS_INCLUDE_SMATRIX=ON \
    -DALGEBRA_PLUGINS_INCLUDE_VECMEM=ON \
    -DALGEBRA_PLUGINS_SETUP_EIGEN3=ON \
    -DALGEBRA_PLUGINS_SETUP_FASTOR=ON \
    -DALGEBRA_PLUGINS_SETUP_VECMEM=ON \
    -DALGEBRA_PLUGINS_BUILD_TESTING=OFF \
    -DCMAKE_INSTALL_PREFIX=${PREFIX}

cmake --build build -j${CPU_COUNT}
cmake --install build
