schema_version: 1

context:
  version: "0.6.1"

package:
  name: alphagenome
  version: ${{ version }}

source:
  url: https://github.com/google-deepmind/alphagenome/archive/v${{ version }}.tar.gz
  sha256: 8aa4db613b3168560cfce1c05a2d30b1bacc0eee297952d2730dd1520fb70346

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python =${{ python_min }}
    - hatchling
    - grpcio-tools <=1.67.1
    - importlib-resources
    - pip
  run:
    - python >=${{ python_min }}
    - absl-py
    - anndata
    - grpcio
    - immutabledict
    - intervaltree
    - jaxtyping
    - matplotlib-base
    - ml_dtypes
    - numpy
    - pandas
    - protobuf
    - pyarrow
    - scipy
    - seaborn
    - tqdm
    - typeguard
    - typing_extensions
    - zstandard

tests:
  - python:
      imports:
        - alphagenome
      pip_check: true

about:
  summary: A Python SDK for interacting and visualizing genomic models.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danielnachun
