schema_version: 1

context:
  version: 0.16.0

package:
  name: r-susier
  version: ${{ version|replace("-", "_") }}

source:
  url: https://github.com/stephenslab/susieR/archive/refs/tags/${{ version }}.tar.gz
  sha256: d5d4fc82dcd36b8a21eb635adee8ff01781121ac651add5dcb1b8998be261394

build:
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - make
  host:
    - r-base
    - r-cpp11
    - r-cpp11armadillo
    - r-crayon
    - r-ggplot2
    - r-glmnet
    - r-l0learn
    - r-matrix
    - r-matrixstats
    - r-mixsqp
    - r-reshape
    - r-rfast
  run:
    - r-base
    - r-cpp11
    - r-cpp11armadillo
    - r-crayon
    - r-ggplot2
    - r-glmnet
    - r-l0learn
    - r-matrix
    - r-matrixstats
    - r-mixsqp
    - r-reshape
    - r-rfast

tests:
  - script:
     - R -e "library('susieR')"

about:
  license: MIT
  summary: |
    Implements methods for variable selection in linear regression based on the "Sum of Single Effects" (SuSiE) model, as described in Wang et al (2020) <DOI:10.1101/501114>. These methods provide simple summaries, called "Credible Sets", for accurately quantifying uncertainty in which variables should be selected.
    The methods are motivated by genetic fine-mapping applications, and are particularly well-suited to settings where variables are highly correlated and detectable effects are sparse. The fitting algorithm, a Bayesian analogue of stepwise selection methods called "Iterative Bayesian Stepwise Selection" (IBSS), is simple
    and fast, allowing the SuSiE model be fit to large data sets (thousands of samples and hundreds of thousands of variables).
  license_file:
    - LICENSE
  homepage: https://github.com/stephenslab/susieR

extra:
  recipe-maintainers:
    - danielnachun
