context:
  version: 1.60.0
  name: snpStats
  bioc: 3.22

package:
  name: bioconductor-${{ name|lower }}
  version: ${{ version }}

source:
  url:
    - https://bioconductor.org/packages/${{ bioc }}/bioc/src/contrib/${{ name }}_${{ version }}.tar.gz
    - https://bioconductor.org/packages/${{ bioc }}/bioc/src/contrib/Archive/${{ name }}/${{ name }}_${{ version }}.tar.gz
    - https://bioarchive.galaxyproject.org/${{ name }}_${{ version }}.tar.gz
    - https://depot.galaxyproject.org/software/bioconductor-${{ name|lower }}/bioconductor-${{ name|lower }}_${{ version }}_src_all.tar.gz
  md5: edcd52705c16690e1b44b50918b5adc4

build:
  number: 0
  dynamic_linking:
    rpaths:
      - lib/R/lib/
      - lib/

requirements:
  host:
    - bioconductor-biocgenerics >=0.56.0,<0.57.0
    - r-base=4.5
    - r-matrix
    - r-survival
    - libblas
    - liblapack
    - zlib
  run:
    - bioconductor-biocgenerics >=0.56.0,<0.57.0
    - r-base=4.5
    - r-matrix
    - r-survival
  build:
    - ${{ compiler('c') }}
    - make

tests:
  - script:
      - R -e "library('${{ name }}')"

about:
  license: GPL-3.0-or-later
  summary: SnpMatrix and XSnpMatrix classes and methods
  description: Classes and statistical methods for large SNP association studies. This extends the earlier snpMatrix package, allowing for uncertainty in genotypes.
  homepage: https://bioconductor.org/packages/${{ bioc }}/bioc/html/${{ name }}.html

extra:
  identifiers:
    - biotools:snpstats
    - doi:10.1038/nmeth.3252
  parent_recipe:
    name: bioconductor-snpstats
    path: recipes/bioconductor-snpstats
    version: 1.30.0
