context:
  version: 0.7.15

package:
  name: bwa_seqlib
  version: ${{ version }}

source:
  url: https://github.com/walaj/bwa/archive/c02766e3c34ac3f4af9842e20a54b7f9f4b36d0b.tar.gz
  sha256: 023ccd462a9d2df24c8dd23e42180081a0800134cac2307ac117c21b0ae0ea8c
  patches:
    - 0001-make-shared-library.patch

build:
  number: 3

requirements:
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - make
    - sed
  host:
    - if: aarch64 or arm64
      then: simde
    - zlib

tests:
  - script:
      - bwa 2>&1 | grep -q "alignment via Burrows-Wheeler transformation"
      - test -f ${PREFIX}/lib/libbwa${SHLIB_EXT}

about:
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: Burrow-Wheeler Aligner for pairwise alignment between DNA sequences (fork for SeqLib)
  homepage: https://github.com/walaj/bwa
  repository: https://github.com/walaj/bwa

extra:
  recipe-maintainers:
    - danielnachun
