schema_version: 1

context:
  version: 1.0.0

package:
  name: watershedr
  version: ${{ version }}

source:
  url: https://github.com/nicolerg/WatershedR/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 8f68f41fed17d8c750c783b063d62670c81e5ea963d40d263e18eb33d21f8071

build:
  number: 1
  dynamic_linking:
    rpaths:
      - lib/R/lib/
      - lib/

requirements:
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
  host:
    - r-base
    - r-lbfgs
    - r-prroc
    - r-rcpp
    - r-rcurl
  run:
    - r-base
    - r-lbfgs
    - r-prroc
    - r-rcpp
    - r-rcurl

tests:
  - script:
      - R -e "library('WatershedR')"

about:
  license: MIT
  summary: Unsupervised probabilistic framework for identifying functional effects of rare variants
  homepage: https://github.com/nicolerg/WatershedR
