MACOSX_DEPLOYMENT_TARGET:
  - '11.0'
c_stdlib_version:
  - if: linux
    then: 2.17
  - if: osx
    then: 11.0
c_stdlib:
  - if: linux
    then: sysroot
  - if: osx
    then: macosx_deployment_target
libblas:
  - 3.9.* *netlib
libcblas:
  - 3.9.* *netlib
liblapack:
  - 3.9.* *netlib
liblapacke:
  - 3.9.* *netlib
blas_impl:
  - openblas
  - if: x86_64
    then:
      - mkl
      - blis
openblas:
  - 0.3.*
mkl:
  - '2025'
r-base:
  - 4.4
  - 4.5
