schema_version: 1

context:
  version: "0.3.0"

package:
  name: r-zarr
  version: ${{ version }}

source:
  url:
    - https://cloud.r-project.org//src/contrib/zarr_${{ version }}.tar.gz
  sha256: af36a2975dfae60d5ae8e064539a5440aff4da20e9a9789cccc632f8a8371198

build:
  number: 0
  noarch: generic
  dynamic_linking:
    rpaths:
      - lib/R/lib/
      - lib/

requirements:
  host:
    - r-base
    - r-r6
    - r-blosc
    - r-jsonlite
  run:
    - r-base
    - r-r6
    - r-blosc
    - r-jsonlite

tests:
  - script:
      - R -e "library('zarr')"

about:
  license: MIT
  summary: The 'Zarr' specification is widely used to build libraries for the storage and retrieval
    of n-dimensional array data from data stores ranging from local file systems to
    the cloud. This package is a native 'Zarr' implementation in R with support for
    all required features of 'Zarr' version 3. It is designed to be extensible such
    that new stores, codecs and extensions can be added easily.
  license_file:
    - LICENSE
  homepage: https://github.com/R-CF/zarr, https://r-cf.github.io/zarr/
