schema_version: 1

context:
  version: 0.2_alpha

package:
  name: apex
  version: ${{ version }}

source:
  url: https://github.com/corbinq/apex/archive/63b605e00766141693a69eee6d630ad8ec3b9de0.zip
  sha256: ba52ddca0eb977c5d8b7692dbcd6677ab084c1d956fcb29157ae0d201e9d9f2a
  patches:
    - 0001-clean-up-CXXFLAGS-and-LDFLAGS.patch
    - 0002-check-for-quick_exit.patch

build:
  number: 1

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - if: linux
      then: binutils
    - curl
    - make
    - sed
  host:
    - eigen
    - krb5
    - libboost-devel
    - htslib
    - spectralib
    - shrinkwrap
    - taywee-args
    - zlib
    - liblzma-devel
    - if: linux
      then: libgomp
      else: llvm-openmp
  ignore_run_exports:
    from_package:
      - krb5
      - libboost

tests:
  - script:
      - apex --help

about:
  license: LicenseRef-OTHER
  summary: Toolkit for QTL mapping and meta-analysis.
  homepage: https://github.com/corbinq/apex
