context:
  version: 0.6.0

package:
  name: r-ctwas
  version: ${{ version }}

source:
  url: https://github.com/xinhe-lab/multigroup_ctwas/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 775962a606736d325abd9ac6b1856546134a051c946450e8c6e8b23f44be033e

build:
  number: 0
  noarch: generic
  dynamic_linking:
    rpaths:
      - lib/R/lib/
      - lib/

requirements:
  host:
    - bioconductor-ensembldb
    - bioconductor-annotationfilter
    - r-amr
    - r-base
    - r-cowplot
    - r-crayon
    - r-data.table
    - r-dplyr
    - r-ggplot2
    - r-ggrepel
    - r-locuszoomr
    - r-logging
    - r-magrittr
    - r-matrix
    - r-mixsqp
    - r-pgenlibr
    - r-r.utils
    - r-readr
    - r-rlang
    - r-rsqlite
    - r-tidyr
  run:
    - bioconductor-ensembldb
    - bioconductor-annotationfilter
    - r-amr
    - r-base
    - r-cowplot
    - r-crayon
    - r-data.table
    - r-dplyr
    - r-ggplot2
    - r-ggrepel
    - r-locuszoomr
    - r-logging
    - r-magrittr
    - r-matrix
    - r-mixsqp
    - r-pgenlibr
    - r-r.utils
    - r-readr
    - r-rlang
    - r-rsqlite
    - r-tidyr

tests:
  - script:
      - R -e "library('ctwas')"

about:
  license: MIT
  license_file: LICENSE
  summary: Identify causal genes in TWAS analysis
  homepage: https://github.com/xinhe-lab/multigroup_ctwas

extra:
  recipe-maintainers:
    - danielnachun
