context:
  version: 0.20

package:
  name: perl-alien-libxml2
  version: ${{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/P/PL/PLICEASE/Alien-Libxml2-${{ version }}.tar.gz
  sha256: 56aae7b339bbeb02f77c5801f57a821be5791b51f43bf7f9062bb3bfa444c328

build:
  number: 0
  script: |
    perl Makefile.PL INSTALLDIRS=site
    make
    make test
    make install
    cp ${PREFIX}/man/man1/perlartistic.1 ${SRC_DIR}
    cp ${PREFIX}/man/man1/perlgpl.1 ${SRC_DIR}

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - make
    - pkg-config
  host:
    - liblzma-devel
    - libxml2
    - perl=5.32
    - perl-alien-build
    - perl-alien-build-plugin-download-gitlab
    - perl-test2-suite
    - zlib
  run:
    - perl=5.32
    - perl-alien-build
    - perl-alien-build-plugin-download-gitlab

tests:
  - perl:
      uses:
        - Alien::Libxml2

about:
  license: Artistic-1.0-Perl OR GPL-1.0-or-later
  license_file:
    - perlartistic.1
    - perlgpl.1
  summary: Install the C libxml2 library on your system
  homepage: https://metacpan.org/pod/Alien::Libxml2
