context:
  version: 1.72.0
  name: preprocessCore
  bioc: 3.22

package:
  name: bioconductor-${{ name|lower }}
  version: ${{ version }}

source:
  url:
    - https://bioconductor.org/packages/${{ bioc }}/bioc/src/contrib/${{ name }}_${{ version }}.tar.gz
    - https://bioconductor.org/packages/${{ bioc }}/bioc/src/contrib/Archive/${{ name }}/${{ name }}_${{ version }}.tar.gz
    - https://bioarchive.galaxyproject.org/${{ name }}_${{ version }}.tar.gz
    - https://depot.galaxyproject.org/software/bioconductor-${{ name|lower }}/bioconductor-${{ name|lower }}_${{ version }}_src_all.tar.gz
  md5: c288c12d10a9a8b02904140e08aa97bd

build:
  number: 0
  dynamic_linking:
    rpaths:
      - lib/R/lib/
      - lib/

requirements:
  host:
    - r-base=4.5
    - libblas
    - liblapack
  run:
    - r-base=4.5
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - automake
    - make

tests:
  - script:
      - R -e "library('${{ name }}')"

about:
  license: LGPL-2.0-or-later
  summary: A collection of pre-processing functions
  description: A library of core preprocessing routines.
  homepage: https://bioconductor.org/packages/${{ bioc }}/bioc/html/${{ name }}.html

extra:
  identifiers:
    - biotools:preprocesscore
    - doi:10.1038/nmeth.3252
  parent_recipe:
    name: bioconductor-preprocesscore
    path: recipes/bioconductor-preprocesscore
    version: 1.42.0
