schema_version: 1

context:
  version: "2.07"

package:
  name: fastlmmc
  version: ${{ version }}

source:
  url: https://download.microsoft.com/download/B/0/9/B095C9A0-C08B-41F7-9C7E-76097E875235/FaSTLMM.207.zip
  sha256: 63ffb9bd6ce4b3b270c4f4b674dd8f9ac352547f2b69b8b333e43fbdccdc6606
  patches:
    - 0001-build-fixes.patch

build:
  number: 0

requirements:
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
  host:
    - if: x86_64
      then: mkl-devel
      else: openblas
    - zlib
  run:
    - if: x86_64
      then: mkl
      else: libopenblas

tests:
  - script:
      - fastlmmc 2>&1 | grep -q "FastLmmC"

about:
  license: MS-RL
  license_file: LICENSE.TXT
  summary: Factored Spectrally Transformed Linear Mixed Model
  homepage: https://www.microsoft.com/en-us/download/details.aspx?id=52559
