context:
  version: 0.1

package:
  name: fermi-lite_seqlib
  version: ${{ version }}

source:
  url: https://github.com/walaj/fermi-lite/archive/5bc90f8d70e2b66184eccbd223a3be714c914365.tar.gz
  sha256: 58c066239929f48383044fde68ba164bdd15edb2ff0603cdcd6c3fe095171008
  patches:
    - 0001-make-shared-library.patch

build:
  number: 2

requirements:
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - make
    - sed
  host:
    - if: arm64 or aarch64
      then: simde
    - zlib

tests:
  - script:
      - "fml-asm 2>&1 | grep -q \"Usage: fml-asm \\[options\\]\""
      - test -f ${PREFIX}/lib/libfml${SHLIB_EXT}

about:
  license: MIT
  license_file: LICENSE.txt
  summary: Standalone C library for assembling Illumina short reads in small regions (SeqLib fork)
  homepage: https://github.com/walaj/fermi-lite
  repository: https://github.com/walaj/fermi-lite

extra:
  recipe-maintainers:
    - danielnachun
