context:
  version: 7.1.17

package:
  name: yabai
  version: ${{ version }}

source:
  url: https://github.com/koekeishiya/yabai/archive/v${{ version }}.tar.gz
  sha256: 6faeadc6dcd014f8406a3db551c25163d245711e7e96c3b2b7d2e286dc51b177

build:
  number: 0
  skip: not osx

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - make

tests:
  - script:
      - yabai --version

about:
  license: MIT
  license_file: LICENSE.txt
  summary: A tiling window manager for macOS based on binary space partitioning
  homepage: https://github.com/koekeishiya/yabai
  repository: https://github.com/koekeishiya/yabai

extra:
  recipe-maintainers:
    - danielnachun
