context:
  version: 0.3.44

package:
  name: r-mr.mashr
  version: ${{ version|replace("-", "_") }}

source:
  url: https://cran.r-project.org/src/contrib/mr.mashr_${{ version }}.tar.gz
  sha256: 2bb6c46610636e3a30fa39286624080cf32d55475a3ae64d210e325d589b17cc

build:
  number: 0
  dynamic_linking:
    rpaths:
      - lib/R/lib/
      - lib/

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
  host:
    - libblas
    - liblapack
    - r-base
    - r-ebnm
    - r-flashier
    - r-mashr
    - r-matrixstats
    - r-mvtnorm
    - r-rcpp
    - r-rcpparmadillo
    - r-rcppparallel
  run:
    - r-base
    - r-ebnm
    - r-flashier
    - r-mashr
    - r-matrixstats
    - r-mvtnorm
    - r-rcpp
    - r-rcpparmadillo
    - r-rcppparallel

tests:
  - script:
      - R -e "library('mr.mashr')"

about:
  license: LicenseRef-Other
  license_file: LICENSE
  summary: |
    Provides an implementation of methods for multivariate
    multiple regression with adaptive shrinkage priors.
  homepage: https://github.com/stephenslab/mr.mash.alpha

extra:
  recipe-maintainers:
    - danielnachun
