{% set name = "docker" %}
{% set version = "26.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/docker/cli/archive/v{{ version }}.tar.gz
  sha256: 73f914421db873d1a19d4d15e8ae21bebc35079f3034f574dfc6cd0449edcf89

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - go-cgo=1.22
    - go-licenses
    - go-md2man

test:
  commands:
    - {{ name }} --help

about:
  home: https://github.com/docker/cli
  license: Apache-2.0
  license_file: 
    - LICENSE
    - license-files/
  summary: Pack, ship and run any application as a lightweight container
  dev_url: https://github.com/docker/cli

extra:
  recipe-maintainers:
    - danielnachun
