context:
  version: 1.0.1

package:
  name: leafcutter2
  version: ${{ version }}

source:
  url: https://github.com/leafcutter2/leafcutter2/archive/LeafCutter2-v${{ version }}.tar.gz
  sha256: 590c9775bb602958fe4e594f6807912a80a636aa23dc5125ee51724a9871a6e3

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - leafcutter2 = leafcutter2.cli:leafcutter2_cli
      - leafcutter2-make-clusters = leafcutter2.cli:make_clusters_cli
      - leafcutter2-transcript-tools = leafcutter2.cli:transcript_tools_cli
      - leafcutter2-star2junc = leafcutter2.cli:star2junc_cli

requirements:
  host:
    - python =3.11
    - setuptools >=61
    - pip
  run:
    - python >=3.11
    - numpy
    - pandas
    - biopython
    - pyfastx
    - bedparse
    - argparse-dataclass
    - setuptools

tests:
  - python:
      imports:
        - leafcutter2
      pip_check: false
  - requirements:
      run:
        - pip
        - python
    script:
      - leafcutter2 --help
      - leafcutter2-make-clusters --help
      - leafcutter2-transcript-tools --help
      - leafcutter2-star2junc --help

about:
  summary: Splicing quantification and classification from RNA-seq junction files
  license: MIT
  homepage: https://github.com/leafcutter2/leafcutter2
