context:
  version: 1.9.11

package:
  name: bgen-py
  version: ${{ version }}

source:
  url: https://pypi.io/packages/source/b/bgen/bgen-${{ version }}.tar.gz
  sha256: d4e10a721ff7000612665432df8006bda103a2fe54e4576c7705dd27f69aa4a9

build:
  number: 0

requirements:
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - if: linux
      then: gcc
    - cmake
    - make
    - sed
  host:
    - cython
    - packaging
    - pip
    - python
    - setuptools
    - zlib
  run:
    - cython
    - numpy
    - python

tests:
  - python:
      imports:
        - bgen

about:
  license: MIT
  license_file:
  summary: Package for loading data from bgen files
  homepage: https://github.com/jeremymcrae/bgen
