schema_version: 1

context:
  version: 12.3.2

package:
  name: mariadb
  version: ${{ version }}

source:
  url: https://archive.mariadb.org/mariadb-${{ version }}/source/mariadb-${{ version }}.tar.gz
  sha256: 82798714baf2f3456ed2f311fc803dc120f2bf3b82358e773847d628cdb4b670
  # patches:
  #   - 0001-fix-o_direct-usage.patch
  #   - 0002-fix-o_direct-usage.patch
  #   - 0003-fix-windows.patch
  #   - 0004-fix-libxml.patch

build:
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - cmake
    - curl
    - git
    - ninja
    - if: unix
      then: bison
      else: m2-bison
  host:
    - libboost-devel
    - bzip2
    - fmt
    - krb5
    - libcurl
    - libxml2
    - lz4-c
    - lzo
    - openssl
    - pcre2
    - snappy
    - xz
    - zlib
    - zstd
    - if: unix
      then:
        - libedit
        - ncurses
  ignore_run_exports:
    from_package:
      - fmt

tests:
  - script:
      - test -f ${PREFIX}/lib/libmariadb${SHLIB_EXT}
      - mariadb 2>&1 | grep -q "Can't read dir of '/etc/my.cnf.d'"

about:
  license: GPL-2.0-only
  license_file: COPYING
  summary: Drop-in replacement for MySQL
  homepage: https://mariadb.org/
  repository: https://github.com/MariaDB/server
