schema_version: 1

context:
  version: 0.2.0

package:
  name: r-mvsusier
  version: ${{ version }}

source:
  url: https://github.com/stephenslab/mvsusieR/archive/${{ version }}.tar.gz
  sha256: 6e596865b9b2f8a67eb60c19bf54745c2355d88f74fd13d541739ee0a58fd199

build:
  number: 0
  dynamic_linking:
    rpaths:
      - lib/R/lib/
      - lib/

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
  host:
    - r-abind
    - r-ashr
    - r-base
    - r-cowplot
    - r-ggplot2
    - r-ggrepel
    - r-mashr
    - r-matrixstats
    - r-mixsqp
    - r-mvtnorm
    - r-rcpp
    - r-rcpparmadillo
    - r-rlang
    - r-susier
  run:
    - r-abind
    - r-ashr
    - r-base
    - r-cowplot
    - r-ggplot2
    - r-ggrepel
    - r-mashr
    - r-matrixstats
    - r-mixsqp
    - r-mvtnorm
    - r-rcpp
    - r-rcpparmadillo
    - r-rlang
    - r-susier

tests:
  - script:
      - R -e "library('mvsusieR')"

about:
  license: GPL-3.0-or-later
  license_file: LICENSE.md
  summary: |
    Implements a multivariate generalization of the "Sum of
    Single Effects" (SuSiE) model for variable selection in multivariate
    linear regression.
  homepage: https://github.com/stephenslab/mvsusier
