{% set version = "1.3" %}
{% set name = "r-peer" %}

package:
  name: {{ name }}
  version: {{ version|replace("-", "_") }}

source:
  git_url: https://github.com/PMBio/peer
  git_rev: 40bc4b2cd92459ce42f44dfe279717436395f3f6

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - eigen
  host:
    - r-base=4.2
  run:
    - r-base>=4.2

test:
  commands:
    - $R -e "library('peer')"           # [not win]

about:
  home: https://github.com/PMBio/peer
  license: MIT
  summary: A factor analysis package

extra:
  recipe-maintainers:
    - danielnachun
