schema_version: 1

context:
  version: 1.0

package:
  name: polyfun
  version: ${{ version }}

source:
  url: https://github.com/omerwe/polyfun/archive/8b17b4ec87fde11f8d216c049c08d1420cd25de6.zip
  sha256: 35c379625881bca77d503297745e466a511fde00f5f6d337e5124156d5b03244
  patches:
    - polyfun-pandas3-bitarray-compat.patch
    - polyfun-pkg_resources-removal.patch

build:
  number: 2
  noarch: generic

requirements:
  run:
    - bgen-py
    - bitarray
    - dask
    - deprecated
    - finemap
    - networkx
    - numpy>=1.26
    - packaging
    - pandas
    - pandas-plink
    - pip
    - pyarrow>=3.0
    - python
    - r-ckmeans.1d.dp
    - r-expm
    - r-lattice
    - r-matrixstats
    - r-susier
    - r-stringi
    - r-wavethresh
    - rpy2>=3.5.9
    - scikit-learn
    - scipy
    - setuptools
    - snappy
    - tqdm
    - xarray

tests:
  - script:
      - aggregate_finemapper_results.py -h
      - compute_ldscores.py -h
      - compute_ldscores_from_ld.py -h
      - create_finemapper_jobs.py -h
      - extract_annotations.py -h
      - extract_snpvar.py -h
      - finemapper.py -h
      - ldsc.py -h
      - munge_polyfun_sumstats.py -h
      - polyfun.py -h
      - polyloc.py -h
      - polypred.py -h

about:
  license: MIT
  license_file: LICENSE
  summary: PolyFun (POLYgenic FUNctionally-informed fine-mapping)
  homepage: https://github.com/omerwe/polyfun
