#!/usr/bin/env bash

set -o xtrace -o nounset -o errexit

export CXXFLAGS="${CXXFLAGS} -I${PREFIX}/include/eigen3 -Wno-return-type -DBOOST_TEST_DYN_LINK -fpermissive"
export AS_NEEDED=""
if [[ ${target_platform} =~ .*linux.* ]]; then
    export AS_NEEDED="-Wl,--no-as-needed"
fi
export LINKFLAGS="${LDFLAGS} ${AS_NEEDED} -lboost_unit_test_framework -lboost_thread -lboost_iostreams -lboost_filesystem -lboost_timer -lzstd -lsqlite3"

sed -i "s/'3rd_party', //" wscript
./waf configure --prefix=${PREFIX}

cat <<EOF > build/release/config/package_revision_autogenerated.hpp
#ifndef PACKAGE_REVISION_HPP
#define PACKAGE_REVISION_HPP
namespace globals {
char const* const package_version = "${PKG_VERSION}" ;
char const* const package_revision = "unknown" ;
}
#endif
EOF

./waf build
./waf install

mv ${PREFIX}/bin/hptest_v${PKG_VERSION} ${PREFIX}/bin/hptest
mv ${PREFIX}/bin/inthinnerator_v${PKG_VERSION} ${PREFIX}/bin/inthinnerator
mv ${PREFIX}/bin/ldbird_v${PKG_VERSION} ${PREFIX}/bin/ldbird
mv ${PREFIX}/bin/qctool_v${PKG_VERSION} ${PREFIX}/bin/qctool
mv ${PREFIX}/bin/selfmap_v${PKG_VERSION} ${PREFIX}/bin/selfmap
