#!/usr/bin/env bash

set -o xtrace -o nounset -o pipefail -o errexit

export CXXFLAGS="${CXXFLAGS} -I${PREFIX}/include/eigen3 -Wno-return-type -DBOOST_TEST_DYN_LINK -fpermissive"
export LINKFLAGS="${LDFLAGS} -lboost_unit_test_framework -lboost_thread -lboost_iostreams -lboost_filesystem -lboost_timer -lzstd -lsqlite3"
if [[ ${target_platform} =~ .*linux.* ]]; then
    export LINKFLAGS="${LINKFLAGS} -Wl,--no-as-needed"
fi

sed -i "s/'3rd_party', //" wscript
./waf configure --prefix=${PREFIX}

cat <<EOF > build/release/config/package_revision_autogenerated.hpp
#ifndef PACKAGE_REVISION_HPP
#define PACKAGE_REVISION_HPP
namespace globals {
char const* const package_version = "${PKG_VERSION}" ;
char const* const package_revision = "unknown" ;
}
#endif
EOF

./waf build
./waf install

ls ${PREFIX}/bin/*_v${PKG_VERSION} | xargs -I % bash -c "mv % ${PREFIX}/bin/\$(basename % _v${PKG_VERSION})"
