schema_version: 1

context:
  version: 1.1.1

package:
  name: phaser
  version: ${{ version }}

source:
  url: https://github.com/secastel/${{ name }}/archive/aa1f8ec5fe1cc676e37cfa6f6a0bce6b09070301.tar.gz
  sha256: 7552f15723130a55a83d1b76fbb5303bf78d1a0d443aea776e0626fd74de3a4a

build:
  number: 3

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - sed
  host:
    - cython
    - python
  run:
    - bcftools
    - intervaltree
    - numpy
    - pandas
    - pysam
    - python
    # - pyvcf
    - scipy
    - samtools
    - bedtools

tests:
  - script:
      - phaser.py -h
      # - phaser_annotate.py -h
      - phaser_gene_ae.py -h
      - phaser_cis_var.py -h
      - phaser_expr_matrix.py -h

about:
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: phasing and Allele Specific Expression from RNA-seq
  homepage: https://github.com/secastel/phaser
  repository: https://github.com/secastel/phaser

extra:
  recipe-maintainers:
    - danielnachun
